[project]
name = "precommit-hooks"
version = "0.3.1"
requires-python = ">=3.9"
dependencies = [
    "ruff>=0.15.4",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[project.scripts]
copyright-check = "hooks.copyright:main"
pytest-run = "hooks.pytest:main"
coverage-check = "hooks.coverage:main"
conventional-commit = "hooks.conventional_commit:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

